Repository suitenumerique/docs, pull requests merged in 2024-05, with the labels that each got.

#47 💚(ci) improve secrets for k8s deployment
  src/helm/env.d/staging/secrets.enc.yaml
  src/helm/env.d/staging/values.impress.yaml.gotmpl
  src/helm/extra/templates/secrets.yaml
  src/helm/helmfile.yaml
Labels: noChangeLog

#54 👷(CI) Frontend environment free
  src/frontend/apps/impress/.env.development
  src/frontend/apps/impress/.env.production
  src/frontend/apps/impress/.env.test
  src/frontend/apps/impress/src/api/__tests__/fetchApi.test.tsx
  src/frontend/apps/impress/src/api/fetchApi.ts
  src/frontend/apps/impress/src/core/auth/useAuthStore.tsx
  src/frontend/apps/impress/src/core/conf.ts
  src/frontend/apps/impress/src/core/index.ts
  src/frontend/apps/impress/src/custom-next.d.ts
  src/frontend/apps/impress/src/features/pads/pad/stores/usePadStore.tsx
  src/frontend/apps/impress/src/features/pads/pads-panel/__tests__/PanelPads.test.tsx
  src/helm/env.d/dev/values.impress.yaml.gotmpl
Labels: enhancement, frontend, CI

#61 💚(CI) increase timeout e2e job
  .github/workflows/impress-frontend.yml
Labels: CI

#69 🔖(minor) initial release to 0.1.0
  CHANGELOG.md
  src/helm/env.d/production/values.impress.yaml.gotmpl
  src/mail/package.json
  src/tsclient/package.json
Labels: release

#72 🔐(helm) add djangoSuperUserEmail secret
  src/helm/env.d/staging/secrets.enc.yaml
  src/helm/env.d/staging/values.impress.yaml.gotmpl
Labels: CI

#77 ♻️(models) rename document/template access rights
  src/backend/core/admin.py
  src/backend/core/api/viewsets.py
  src/backend/core/migrations/0001_initial.py
  src/backend/core/migrations/0002_alter_user_language_invitation_and_more.py
  src/backend/core/models.py
  src/backend/core/tests/documents/test_api_documents_delete.py
  src/backend/core/tests/documents/test_api_documents_retrieve.py
  src/backend/core/tests/documents/test_api_documents_update.py
  src/backend/core/tests/templates/test_api_templates_delete.py
  src/backend/core/tests/templates/test_api_templates_retrieve.py
  src/backend/core/tests/templates/test_api_templates_update.py
  src/backend/core/tests/test_api_document_accesses.py
  src/backend/core/tests/test_api_document_invitations.py
  src/backend/core/tests/test_api_document_versions.py
  src/backend/core/tests/test_api_template_accesses.py
  src/backend/core/tests/test_models_document_accesses.py
  src/backend/core/tests/test_models_documents.py
  src/backend/core/tests/test_models_invitations.py
  src/backend/core/tests/test_models_template_accesses.py
  src/backend/core/tests/test_models_templates.py
  src/frontend/apps/impress/src/features/pads/pad-management/types.tsx
  src/frontend/apps/impress/src/features/pads/pad-tools/types.ts
Labels: enhancement, python, noChangeLog, backend

#63 Docker impress dev
  CHANGELOG.md
  Makefile
  README.md
  docker-compose.yml
  src/frontend/Dockerfile
Labels: enhancement, docker
