Repository suitenumerique/docs, pull requests merged in 2025-05, with the labels that each got.

#911 🚩(frontend) version MIT only
  .github/workflows/docker-hub.yml
  CHANGELOG.md
  docker-compose.yml
  src/frontend/Dockerfile
  src/frontend/apps/impress/.env
  src/frontend/apps/impress/.env.development
  src/frontend/apps/impress/src/custom-next.d.ts
  src/frontend/apps/impress/src/features/docs/doc-header/__tests__/DocToolBox.spec.tsx
  src/frontend/apps/impress/src/features/docs/doc-header/__tests__/DocToolBoxAGPL.spec.tsx
  src/frontend/apps/impress/src/features/docs/doc-header/__tests__/DocToolBoxMIT.spec.tsx
  src/frontend/apps/impress/src/features/docs/doc-header/components/DocToolBox.tsx
  src/frontend/apps/impress/src/features/docs/doc-header/components/DocToolBoxLicenceAGPL.tsx
  src/frontend/apps/impress/src/features/docs/doc-header/components/DocToolBoxLicenceMIT.tsx
  src/frontend/apps/impress/src/features/docs/doc-header/hooks/useCopyCurrentEditorToClipboard.tsx
Labels: frontend, CI, feature, export

#958 📝(project) add missing env var to env.md
  docs/env.md
Labels: documentation

#977 ✨(backend) allow setting session cookie age via env var
  CHANGELOG.md
  docs/env.md
  src/backend/impress/settings.py
Labels: documentation, python, backend, reusability, self-host

#990 🐛(tilt) update certificate path for Python 3.13 upgrade
  src/helm/env.d/dev/values.impress.yaml.gotmpl
Labels: noChangeLog

#989 fix document converter with large transcript
  CHANGELOG.md
  src/frontend/servers/y-provider/__tests__/server.test.ts
  src/frontend/servers/y-provider/src/servers/appServer.ts
Labels: bug, enhancement
