Repository suitenumerique/docs, pull requests merged in 2025-06, with the labels that each got.

#1005 📌(yjs) stop pinning node to minor version on yjs docker image
  CHANGELOG.md
  src/frontend/servers/y-provider/Dockerfile
Labels: dependencies, javascript, docker, y.js

#1088 🐛(env) update yprovider env for local development
  env.d/development/common.dist
  env.d/development/common.e2e.dist
Labels: bug, docker

#1070 📝(readme) fix some small issues in the README
  README.md
Labels: documentation

#1099 ✨(backend) allow to disable checking unsafe mimetype on attachment upload
  CHANGELOG.md
  docs/env.md
  src/backend/core/api/serializers.py
  src/backend/core/tests/documents/test_api_documents_attachment_upload.py
  src/backend/impress/settings.py
Labels: enhancement

#1095 🔥(frontend) remove Beta from logo
  CHANGELOG.md
  src/frontend/apps/e2e/__tests__/app-impress/footer.spec.ts
  src/frontend/apps/e2e/__tests__/app-impress/home.spec.ts
  src/frontend/apps/impress/cunningham.ts
  src/frontend/apps/impress/src/cunningham/cunningham-tokens.css
  src/frontend/apps/impress/src/cunningham/cunningham-tokens.ts
  src/frontend/apps/impress/src/features/header/components/Title.tsx
Labels: frontend
