Repository suitenumerique/docs, pull requests merged in 2025-01, with the labels that each got.

#541 🐛(CI) fix ci
  src/helm/impress/templates/secrets.yaml
Labels: helm

#542 🔧(helm) add option to configure deployment annotations
  src/helm/helmfile.yaml
  src/helm/impress/Chart.yaml
  src/helm/impress/README.md
  src/helm/impress/generate-readme.sh
  src/helm/impress/templates/backend_deployment.yaml
  src/helm/impress/templates/frontend_deployment.yaml
  src/helm/impress/templates/yprovider_deployment.yaml
  src/helm/impress/values.yaml
Labels: helm

#548 🌐(frontend) add last translations
  src/backend/locale/de_DE/LC_MESSAGES/django.mo
  src/backend/locale/de_DE/LC_MESSAGES/django.po
  src/frontend/apps/e2e/__tests__/app-impress/doc-member-create.spec.ts
  src/frontend/apps/impress/src/features/docs/doc-share/components/DocShareModal.tsx
  src/frontend/apps/impress/src/features/docs/doc-share/hooks/useTranslatedShareSettings.tsx
  src/frontend/apps/impress/src/i18n/translations.json
Labels: frontend, i18n

#550 🔖(major) release 2.0.0
  CHANGELOG.md
  src/backend/pyproject.toml
  src/frontend/apps/e2e/package.json
  src/frontend/apps/impress/package.json
  src/frontend/package.json
  src/frontend/packages/eslint-config-impress/package.json
  src/frontend/packages/i18n/package.json
  src/frontend/servers/y-provider/package.json
  src/helm/helmfile.yaml
  src/mail/package.json
Labels: release

#572 📝(doc) fixes in new readme.md
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docs/assets/docs-logo.png
  docs/assets/europe<3opensource.png
  docs/assets/logo-docs.png
  docs/assets/logo.png
Labels: documentation

#594 🔖(minor) release 2.1.0
  CHANGELOG.md
  src/backend/pyproject.toml
  src/frontend/apps/e2e/package.json
  src/frontend/apps/impress/package.json
  src/frontend/package.json
  src/frontend/packages/eslint-config-impress/package.json
  src/frontend/packages/i18n/package.json
  src/frontend/servers/y-provider/package.json
  src/helm/helmfile.yaml
  src/helm/impress/Chart.yaml
  src/mail/package.json
Labels: release

#598 ✏️(readme) fix a few typos
  README.md
Labels: documentation, noChangeLog
