Repository suitenumerique/docs, pull requests merged in 2025-08, with the labels that each got.

#1248 🌐(frontend) set html lang attribute dynamically based on current loc
  CHANGELOG.md
  src/frontend/apps/e2e/__tests__/app-impress/language.spec.ts
  src/frontend/apps/impress/src/i18n/config.ts
  src/frontend/apps/impress/src/i18n/initI18n.ts
  src/frontend/apps/impress/src/pages/_document.tsx
Labels: frontend, accessibility

#1258 🔧(project) Add trailing slash to yprovider api path
  env.d/production.dist/yprovider
Labels: bug

#1249 📝(doc) Fix commands in docker compose section
  docs/installation/compose.md
Labels: documentation

#1270 ✨(frontend) improve accessibility of global docs home link at top
  CHANGELOG.md
  src/frontend/apps/e2e/__tests__/app-impress/header.spec.ts
  src/frontend/apps/impress/src/features/header/components/Header.tsx
  src/frontend/apps/impress/src/i18n/translations.json
Labels: frontend, accessibility

#1272 ⬆️(dependencies) update js dependencies
  src/frontend/apps/e2e/package.json
  src/frontend/apps/impress/package.json
  src/frontend/apps/impress/src/features/docs/doc-export/types.ts
  src/frontend/apps/impress/src/features/service-worker/RequestSerializer.ts
  src/frontend/apps/impress/src/pages/globals.css
  src/frontend/package.json
  src/frontend/packages/eslint-config-impress/package.json
  src/frontend/packages/i18n/package.json
  src/frontend/servers/y-provider/package.json
  src/frontend/yarn.lock
Labels: dependencies

#1263 🐛 Fix some windows compatibilities
  CHANGELOG.md
  Makefile
  bin/_config.sh
  docs/troubleshoot.md
Labels: bug, docker

#1275 ✨(frontend) improve accessibility of search modal for screen readers
  CHANGELOG.md
  src/frontend/apps/e2e/__tests__/app-impress/doc-editor.spec.ts
  src/frontend/apps/e2e/__tests__/app-impress/doc-header.spec.ts
  src/frontend/apps/e2e/__tests__/app-impress/doc-tree.spec.ts
  src/frontend/apps/e2e/__tests__/app-impress/doc-visibility.spec.ts
  src/frontend/apps/e2e/__tests__/app-impress/utils-share.ts
  src/frontend/apps/impress/src/components/DropButton.tsx
  src/frontend/apps/impress/src/components/dropdown-menu/DropdownMenu.tsx
  src/frontend/apps/impress/src/components/quick-search/QuickSearchInput.tsx
  src/frontend/apps/impress/src/features/docs/doc-editor/components/DocEditor.tsx
  src/frontend/apps/impress/src/features/docs/doc-share/components/DocShareModalFooter.tsx
  src/frontend/apps/impress/src/features/docs/doc-share/components/DocVisibility.tsx
  src/frontend/apps/impress/src/i18n/translations.json
Labels: frontend, accessibility

#1298 ♻️(backend) fallback to email identifier when no name
  CHANGELOG.md
  src/backend/core/api/serializers.py
  src/backend/core/tests/serializers/test_user_light_serializer.py
Labels: enhancement

#1315 👷(CI) trigger bundle-size-check only if necessary
  .github/workflows/impress-frontend.yml
Labels: CI
